### ISSUE TITLE
Not compatible with Shamiko

### ISSUE THREAD

**Issue by Lutra-Fs** [AdguardTeam/adguardcert#16]

**Comment by srccrow** [comment]
Not compatibile with Shamiko because of new way to handle hide Zygisk.

**Comment by srccrow** [comment]
Well, looking at logcat I got a libchrome crash followed by a selinux denial, so I guess it's a problem that affects latest bromite release.

Bromite 100.0.4896.92 works fine

**Comment by srccrow** [comment]
https://github.com/bromite/bromite/issues/2067 

Check this with latest release, reverting to old Bromite is ok, so it's either a bug or a measure to prevent using this.

**Comment by srccrow** [comment]
Hmm, problem is probably not Shamiko or Bromite specific but upstream chromium change, not sure.

**Comment by Lutra-Fs** [comment]
This module is rely on denylist while shamiko's working process is requiring disable denylist.

**Comment by srccrow** [comment]
Well, in my case the AdGuard Cert is not creating problems, just recompiled the module excluding the affected browser. ^-^

**Comment by srccrow** [comment]
@Lutra-Fs You right, can we talk to Shamiko and say this cause problems also using Bromite? I tried also downgrading to lower version of Shamiko it seems it affect only chromium >= 101 so far

**Comment by sfionov** [comment]
We have a better workaround with intermediate cert, that doesn't require Zygisk. It will be released in upcoming weeks.

**Comment by coxackie** [comment]
Well, I do not know what the definition of 'upcoming' is, but I would guess it is not more than 13... Could you please fix this issue?

**Comment by adzkii-i** [comment]
could we get an update on this?

**Comment by sfionov** [comment]
This is expected to be fixed in Adguard for Android 4.0 release.

However, new 4.0 codebase has not reached nighties yet.

So, ETA is still unknown at this point. We will post an update when they will be.

**Comment by Carlos920** [comment]
> This is expected to be fixed in Adguard for Android 4.0 release.
> 
> However, new 4.0 codebase has not reached nighties yet.
> 
> So, ETA is still unknown at this point. We will post an update when they will be.

Is this problem fixed now?

**Comment by pannal** [comment]
Where are we with this? 4.0 is out.

**Comment by sfionov** [comment]
Hello!

Two certificate method has been implemented in AdGuard for Android 4.2 nightly 11 + adguardcert v2.0-beta4.

Now module does not require Zygisk.

**Comment by Lutra-Fs** [comment]
Thank you for your excellent work. Would it be possible to close this issue once the solution is included in the release version?

**Comment by privacyguy123** [comment]
I had no idea Shamiko/Enforce off even affected this module. A short writeup on one of the webpages would have been nice. ;) 

I guess it's not needed with this new upcoming release. Can you comment on whether or not it'll be safe to add "All Apps HTTPS Filtered" with this new Adguard app/module combo?
