### ISSUE TITLE
Proper Fix Instead of Workaround

### ISSUE THREAD

**Issue by christantoan** [AdguardTeam/adguardcert#21]
From [Knowledge Base](https://kb.adguard.com/en/general/https-filtering/https-filtering-known-issues#certificate-transparency)  should properly fix this issue, no?
How's the progress on this as the ETA has almost past 1 year.

**Comment by takattowo** [comment]
I don't think they really care about this, given the fact had not replied to any reported issue,

**Comment by sfionov** [comment]
Hello! CT check is a part of validation library. Of course it should be implemented (we have a plan for it). But implementing it doesn't eliminate need of this workaround.

We have a better workaround with intermediate cert, that doesn't require Zygisk. It will be released in upcoming weeks.

**Comment by cxplay** [comment]
> Hello! CT check is a part of validation library. Of course it should be implemented (we have a plan for it). But implementing it doesn't eliminate need of this workaround.
> 
> We have a better workaround with intermediate cert, that doesn't require Zygisk. It will be released in upcoming weeks.

So, where is it?

**Comment by sfionov** [comment]
Adguard for Android 4.2+ contains both two cert scheme and CT check in validation library
