### ISSUE TITLE
request compatible with Riru mode

### ISSUE THREAD

**Issue by zongh4n** [AdguardTeam/adguardcert#27]
the module is support Zygisk only, hope it can be compatible with Riru mode.

**Comment by steupz** [comment]
The 2.0 does that if you can build it

**Comment by zongh4n** [comment]
> The 2.0 does that if you can build it

Bro, thanks for your noti. but I dont know how build it, and I tried find out the end product in Actions but no luck. :-/

**Comment by innit86** [comment]
> the module is support Zygisk only, hope it can be compatible with Riru mode.

You can download version 2.0 from AdGuard's official Telegram channel https://t.me/adguard_en/207096
