### ISSUE TITLE
Does Firefox use these certificates?

### ISSUE THREAD

**Issue by daiaji** [AdguardTeam/adguardcert#31]
To be honest, I am planning to use an anti-censorship software that requires a custom CA to tamper with HTTPS traffic. I am planning to modify your magisk module to install a custom CA provided by that software.

But I don't know if Firefox requires additional Settings to use these CAs.

**Comment by uaevuon** [comment]
Which app do you referring to?

**Comment by daiaji** [comment]
In fact, it doesn't work. Some sites can't use custom CA even if firefox has some options enabled, and generally only programs like HttpCanary seem to work.
