### ISSUE TITLE
Is this open source? There's no license 

### ISSUE THREAD

**Issue by pimterry** [AdguardTeam/adguardcert#57]
I assume this intended to be GPL, like the other public adguardteam repos, but it's not explicit. It would be great if there was a LICENSE file in this repo to make that clear.

I'm the author of https://httptoolkit.com/blog/android-14-install-system-ca-certificate/, which you may have seem (it looks like you are using that exact solution here). I'd like to pull in some of the improvements you've used on top (like set_context for example) and it'd be good to know for sure that that's OK.

**Comment by ameshkov** [comment]
@pimterry thank you for the question!

@sfionov let's make it something very simple, Apache or MIT, no need for GPL here.

**Comment by pimterry** [comment]
Awesome, thanks for the quick fix @sfionov & @ameshkov!
